#   _____  _    _  _____ ______  _____ ___  ___ _____  _   _  _____
#  /  ___|| |  | ||_   _||  ___||_   _||  \/  ||_   _|| \ | ||  ___|
#  \ `--. | |  | |  | |  | |_     | |  | .  . |  | |  |  \| || |__
#   `--. \| |/\| |  | |  |  _|    | |  | |\/| |  | |  | . ` ||  __|
#  /\__/ /\  /\  / _| |_ | |      | |  | |  | | _| |_ | |\  || |___
#  \____/  \/  \/  \___/ \_|      \_/  \_|  |_/ \___/ \_| \_/\____/
#
#                           VERSION 1.0.0
#                         PLUGIN BY KYOCUTI

